### ISSUE TITLE
jQuery 1.11.0 link is borken 

### ISSUE THREAD

**Issue by YiyangLi** [fardream/d3knockoutjs#1]
"script src="https://code.jquery.com/jquery-1.11.0.min.js""
the https is missing. 

And another minor thing. it would be better to use SASS to generate your CSS file, you could even dynamically draw the point color by apoint(x, y, y0, color), where color is a Hex value like 0xFFFFFF

http://sass-lang.com/styleguide/code/

**Comment by fardream** [comment]
Thanks for the advices. SASS or LESS is not used because the example is meant to be very simple and self-contained.
